replicaCount: 2

image:
  repository: fincore
  tag: "8"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: mysql
  DB_URL: "jdbc:mysql://mysql:3306/enterprise_banking?createDatabaseIfNotExist=true&serverTimezone=UTC"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MONGODB_URI: "mongodb://mongo:27017/fincore_audit"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 768Mi

mysql:
  image: mysql:8.4
  database: enterprise_banking
  storage: 2Gi

redis:
  image: redis:7.4-alpine

mongo:
  image: mongo:8.0