apiVersion: v1
kind: ConfigMap
metadata:
  name: fincore-config
data:
  SPRING_PROFILES_ACTIVE: mysql
  DB_URL: jdbc:mysql://mysql:3306/enterprise_banking?createDatabaseIfNotExist=true&serverTimezone=UTC
  REDIS_HOST: redis
  MONGODB_URI: mongodb://mongo:27017/fincore_audit
