apiVersion: apps/v1
kind: Deployment
metadata:
  name: fincore

spec:
  replicas: 2

  selector:
    matchLabels:
      app: fincore

  template:
    metadata:
      labels:
        app: fincore

    spec:
      containers:
        - name: fincore
          image: fincore:7
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: fincore-config
            - secretRef:
                name: fincore-secrets

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: fincore

spec:
  selector:
    app: fincore

  ports:
    - port: 80
      targetPort: 8080