{
 "title": "FinCore Enterprise Banking - Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FinCore Pods UP",
   "type": "stat",
   "description": "FinCore Enterprise Banking - Monitoring",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"fincore-helm-fincore\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FinCore JVM Heap Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",service=\"fincore-helm-fincore\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FinCore CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{service=\"fincore-helm-fincore\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FinCore HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"fincore-helm-fincore\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FinCore HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_server_requests_seconds_sum{service=\"fincore-helm-fincore\"}[1m]))\r\n/\r\n  sum(rate(http_server_requests_seconds_count{service=\"fincore-helm-fincore\"}[1m]))\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FinCore HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      service=\"fincore-helm-fincore\",\r\n      status=~\"5..\"\r\n    }[1m]\r\n  )\r\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FinCore MySQL Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{service=\"fincore-helm-fincore\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}