apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fincore-config

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
  DB_URL: {{ .Values.env.DB_URL | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  MONGODB_URI: {{ .Values.env.MONGODB_URI | quote }}