apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fincore-config

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
  DB_URL: {{ printf "jdbc:mysql://%s-mysql:3306/%s?createDatabaseIfNotExist=true&serverTimezone=UTC" .Release.Name .Values.mysql.database | quote }}
  REDIS_HOST: {{ printf "%s-redis" .Release.Name | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  MONGODB_URI: {{ printf "mongodb://%s-mongo:27017/fincore_audit" .Release.Name | quote }}