apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fincore

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: fincore
      instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: fincore
        instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: fincore

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-fincore-config

            - secretRef:
                name: fincore-secrets

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 20