package com.sakti.banking.service;
import com.sakti.banking.dto.*; import com.sakti.banking.entity.*; import com.sakti.banking.exception.*; import com.sakti.banking.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.security.SecureRandom; import java.time.*; import java.util.*;
@Service public class AccountService { private final AccountRepository accounts; private final TransactionRepository txs; private final UserService users; private final AuditService audit; private final SecureRandom random=new SecureRandom(); public AccountService(AccountRepository a,TransactionRepository t,UserService u,AuditService au){accounts=a;txs=t;users=u;audit=au;}
 @Transactional public AccountResponse create(String email,CreateAccountRequest r){AppUser owner=users.requireByEmail(email); if(accounts.existsByOwnerIdAndAccountTypeAndStatusNot(owner.getId(),r.accountType(),AccountStatus.CLOSED)) throw new BusinessException("You already have an active "+r.accountType()+" account"); BankAccount a=new BankAccount();a.setAccountNumber(generateAccountNumber());a.setAccountType(r.accountType());a.setOwner(owner);a.setBalance(BigDecimal.ZERO);a=accounts.save(a);audit.record(email,"ACCOUNT_CREATE",a.getAccountNumber(),"SUCCESS");return AccountResponse.from(a);} 
 @Transactional(readOnly=true) public List<AccountResponse> myAccounts(String email){return accounts.findByOwnerEmailIgnoreCase(email).stream().map(AccountResponse::from).toList();}
 @Transactional public AccountResponse deposit(String email,String n,MoneyRequest r){BankAccount a=requireOwnedLocked(email,n);requireActive(a);a.setBalance(a.getBalance().add(r.amount()));saveTx(a,TransactionType.DEPOSIT,r.amount(),r.description(),null);audit.record(email,"DEPOSIT",n,"SUCCESS");return AccountResponse.from(a);} 
 @Transactional public AccountResponse withdraw(String email,String n,MoneyRequest r){BankAccount a=requireOwnedLocked(email,n);requireActive(a);if(a.getBalance().compareTo(r.amount())<0)throw new BusinessException("Insufficient balance");a.setBalance(a.getBalance().subtract(r.amount()));saveTx(a,TransactionType.WITHDRAWAL,r.amount(),r.description(),null);audit.record(email,"WITHDRAW",n,"SUCCESS");return AccountResponse.from(a);} 
 @Transactional public void transfer(String email,TransferRequest r){if(r.fromAccount().equals(r.toAccount()))throw new BusinessException("Source and destination accounts must differ");String first=r.fromAccount().compareTo(r.toAccount())<0?r.fromAccount():r.toAccount();String second=first.equals(r.fromAccount())?r.toAccount():r.fromAccount();BankAccount a=accounts.findWithLockByAccountNumber(first).orElseThrow(()->new ResourceNotFoundException("Account not found: "+first));BankAccount b=accounts.findWithLockByAccountNumber(second).orElseThrow(()->new ResourceNotFoundException("Account not found: "+second));BankAccount from=a.getAccountNumber().equals(r.fromAccount())?a:b;BankAccount to=from==a?b:a;if(!from.getOwner().getEmail().equalsIgnoreCase(email))throw new BusinessException("You do not own the source account");requireActive(from);requireActive(to);if(from.getBalance().compareTo(r.amount())<0)throw new BusinessException("Insufficient balance");from.setBalance(from.getBalance().subtract(r.amount()));to.setBalance(to.getBalance().add(r.amount()));saveTx(from,TransactionType.TRANSFER_OUT,r.amount(),r.description(),to.getAccountNumber());saveTx(to,TransactionType.TRANSFER_IN,r.amount(),r.description(),from.getAccountNumber());audit.record(email,"TRANSFER",from.getAccountNumber()+"->"+to.getAccountNumber(),"SUCCESS");}
 @Transactional(readOnly=true) public List<TransactionResponse> transactions(String email,String n){BankAccount a=accounts.findByAccountNumber(n).orElseThrow(()->new ResourceNotFoundException("Account not found"));if(!a.getOwner().getEmail().equalsIgnoreCase(email))throw new BusinessException("You do not own this account");return txs.findByAccountAccountNumberOrderByCreatedAtDesc(n).stream().map(TransactionResponse::from).toList();}
 @Transactional public AccountResponse requestClosure(String email,String n){BankAccount a=requireOwnedLocked(email,n);if(a.getBalance().compareTo(BigDecimal.ZERO)!=0)throw new BusinessException("Account balance must be zero before closure");if(a.getStatus()==AccountStatus.CLOSED)throw new BusinessException("Account already closed");a.setStatus(AccountStatus.CLOSURE_REQUESTED);audit.record(email,"ACCOUNT_CLOSURE_REQUEST",n,"SUCCESS");return AccountResponse.from(a);} 
 @Transactional public AccountResponse setStatus(String n,AccountStatus status){BankAccount a=accounts.findWithLockByAccountNumber(n).orElseThrow(()->new ResourceNotFoundException("Account not found"));if(status==AccountStatus.CLOSED&&a.getBalance().compareTo(BigDecimal.ZERO)!=0)throw new BusinessException("Cannot close account with non-zero balance");a.setStatus(status);if(status==AccountStatus.CLOSED)a.setClosedAt(LocalDateTime.now());return AccountResponse.from(a);} 
 @Transactional(readOnly=true) public DashboardResponse dashboard(String email){AppUser u=users.requireByEmail(email);List<AccountResponse> list=myAccounts(email);BigDecimal total=list.stream().filter(a->a.status()!=AccountStatus.CLOSED).map(AccountResponse::balance).reduce(BigDecimal.ZERO,BigDecimal::add);List<TransactionResponse> recent=list.stream().filter(a->a.status()!=AccountStatus.CLOSED).flatMap(a->transactions(email,a.accountNumber()).stream()).sorted(Comparator.comparing(TransactionResponse::createdAt).reversed()).limit(10).toList();return new DashboardResponse(UserResponse.from(u),list,total,recent);} 
 private void requireActive(BankAccount a){if(a.getStatus()!=AccountStatus.ACTIVE)throw new BusinessException("Account is not active: "+a.getStatus());} private BankAccount requireOwnedLocked(String e,String n){BankAccount a=accounts.findWithLockByAccountNumber(n).orElseThrow(()->new ResourceNotFoundException("Account not found"));if(!a.getOwner().getEmail().equalsIgnoreCase(e))throw new BusinessException("You do not own this account");return a;} private void saveTx(BankAccount a,TransactionType type,BigDecimal amt,String d,String c){BankTransaction t=new BankTransaction();t.setReference(UUID.randomUUID().toString());t.setType(type);t.setAmount(amt);t.setBalanceAfter(a.getBalance());t.setDescription(d);t.setAccount(a);t.setCounterpartyAccount(c);txs.save(t);} private String generateAccountNumber(){String n;do{n="10"+String.format("%010d",random.nextLong(10_000_000_000L));}while(accounts.findByAccountNumber(n).isPresent());return n;}
}
